name: flutter_application_depi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  http: ^1.3.0
  lottie: ^3.2.0
  firebase_core: ^3.12.1
  animated_splash_screen: ^1.3.0
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  awesome_dialog: ^3.2.1
  wheel_chooser: ^1.1.2
  animated_bottom_navigation_bar: ^1.4.0
  intl: ^0.20.2
  date_format: ^2.0.9
  shared_preferences: ^2.3.3
  permission_handler: ^12.0.0+1
  pedometer: ^4.1.1
  heart_bpm: ^2.0.0+0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.65.0
  flutter_picker: ^2.1.0
  go_router: ^15.1.1
  youtube_player_flutter: ^9.1.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  flutter_spinkit: ^5.2.1
  daily_pedometer2: ^1.1.3
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/
   - assets/notifications/
   - assets/workout_done/
   - assets/achievement/png/
   - assets/bmi/
   - assets/profile/
   - assets/auth/
   - assets/exercises/
   - assets/achievement/strength_2.jpg
   - assets/profile/gym.jpg
