// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIy4_jQeMk3BDQLM4n8CpIFiTTabx1EyE',
    appId: '1:819905247319:web:6a8861d9ed0de80b010b12',
    messagingSenderId: '819905247319',
    projectId: 'fluttercourse-5af65',
    authDomain: 'fluttercourse-5af65.firebaseapp.com',
    storageBucket: 'fluttercourse-5af65.appspot.com',
    measurementId: 'G-5N7LQ39D2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMy968UAI1YI71Mg2vHQikFqNEDra4_o8',
    appId: '1:819905247319:android:da32dbf68ec1b0e8010b12',
    messagingSenderId: '819905247319',
    projectId: 'fluttercourse-5af65',
    storageBucket: 'fluttercourse-5af65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIyqcrFHoZyE1YUzOZcD7ZyPVYaBc7LIM',
    appId: '1:819905247319:ios:df3b10c5aa39de47010b12',
    messagingSenderId: '819905247319',
    projectId: 'fluttercourse-5af65',
    storageBucket: 'fluttercourse-5af65.appspot.com',
    androidClientId: '819905247319-ma8bouc9922p3gvop23btmba7pr5a9h8.apps.googleusercontent.com',
    iosClientId: '819905247319-ep7v403mv1ikf8p7lrnppm19g96b1t15.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationDepi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIyqcrFHoZyE1YUzOZcD7ZyPVYaBc7LIM',
    appId: '1:819905247319:ios:df3b10c5aa39de47010b12',
    messagingSenderId: '819905247319',
    projectId: 'fluttercourse-5af65',
    storageBucket: 'fluttercourse-5af65.appspot.com',
    androidClientId: '819905247319-ma8bouc9922p3gvop23btmba7pr5a9h8.apps.googleusercontent.com',
    iosClientId: '819905247319-ep7v403mv1ikf8p7lrnppm19g96b1t15.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationDepi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIy4_jQeMk3BDQLM4n8CpIFiTTabx1EyE',
    appId: '1:819905247319:web:a5f2ce885d11bcc7010b12',
    messagingSenderId: '819905247319',
    projectId: 'fluttercourse-5af65',
    authDomain: 'fluttercourse-5af65.firebaseapp.com',
    storageBucket: 'fluttercourse-5af65.appspot.com',
    measurementId: 'G-R7VP802N3S',
  );

}